<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<TargetFramework>$(framework)</TargetFramework>
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoYuBlazor.Application\MoYuBlazor.Application.csproj" />
	</ItemGroup>

</Project>
