<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<TargetFramework>$(framework)</TargetFramework>
		<NoWarn>1701;1702;1591</NoWarn>
		<DocumentationFile>MoYuRazorApi.Web.Core.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="MoYuRazorApi.Web.Core.xml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoYuRazorApi.Application\MoYuRazorApi.Application.csproj" />
		<ProjectReference Include="..\MoYuRazorApi.Database.Migrations\MoYuRazorApi.Database.Migrations.csproj" />
	</ItemGroup>

</Project>
