<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<TargetFramework>$(framework)</TargetFramework>
		<NoWarn>1701;1702;1591</NoWarn>
		<DocumentationFile>MoYuBlazorApi.Web.Core.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="MoYuBlazorApi.Web.Core.xml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoYuBlazorApi.Application\MoYuBlazorApi.Application.csproj" />
	</ItemGroup>

</Project>
