<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn>1701;1702;1591</NoWarn>
		<DocumentationFile>MoYu.Web.Core.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="MoYu.Web.Core.xml" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoYu.Application\MoYu.Application.csproj" />
		<ProjectReference Include="..\MoYu.Database.Migrations\MoYu.Database.Migrations.csproj" />
	</ItemGroup>

</Project>
